# Analysis of the California Regional Multiple Listing Service (CRMLS) Data

This will explore datasets related to Califlornia real estate data from January 2024 - July 2026

<hr>

by: YuLi Lin

### **Week 1** — Monthly Dataset Aggregation

In [219]:
# imports
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
import numpy as np

In [220]:
#Aggregating all listing files into "list"
list1 = pd.read_csv("CRMLSListing202401.csv", low_memory = False)
list2 = pd.read_csv("CRMLSListing202402.csv", low_memory = False)
list3 = pd.read_csv("CRMLSListing202403.csv", low_memory = False)
list4 = pd.read_csv("CRMLSListing202404.csv", low_memory = False)
list5 = pd.read_csv("CRMLSListing202405.csv", low_memory = False)
list6 = pd.read_csv("CRMLSListing202406.csv", low_memory = False)
list7 = pd.read_csv("CRMLSListing202407.csv", low_memory = False)
list8 = pd.read_csv("CRMLSListing202408.csv", low_memory = False)
list9 = pd.read_csv("CRMLSListing202409.csv", low_memory = False)
list10 = pd.read_csv("CRMLSListing202410.csv", low_memory = False)
list11 = pd.read_csv("CRMLSListing202411.csv", low_memory = False)
list12 = pd.read_csv("CRMLSListing202412.csv", low_memory = False)
list13 = pd.read_csv("CRMLSListing202501.csv", low_memory = False)
list14 = pd.read_csv("CRMLSListing202502.csv", low_memory = False)
list15 = pd.read_csv("CRMLSListing202503.csv", low_memory = False)
list16 = pd.read_csv("CRMLSListing202504.csv", low_memory = False)
list17 = pd.read_csv("CRMLSListing202505.csv", low_memory = False)
list18 = pd.read_csv("CRMLSListing202506.csv", low_memory = False)
list19 = pd.read_csv("CRMLSListing202507.csv", low_memory = False)
list20 = pd.read_csv("CRMLSListing202508.csv", low_memory = False)
list21 = pd.read_csv("CRMLSListing202509.csv", low_memory = False)
list22 = pd.read_csv("CRMLSListing202510.csv", low_memory = False)
list23 = pd.read_csv("CRMLSListing202511.csv", low_memory = False)
list24 = pd.read_csv("CRMLSListing202512.csv", low_memory = False)
list25 = pd.read_csv("CRMLSListing202601.csv", low_memory = False)
list26 = pd.read_csv("CRMLSListing202602.csv", low_memory = False)
list27 = pd.read_csv("CRMLSListing202603.csv", low_memory = False)
list28 = pd.read_csv("CRMLSListing202604.csv", low_memory = False)
list29 = pd.read_csv("CRMLSListing202605.csv", encoding="cp1252", low_memory = False)
list30 = pd.read_csv("CRMLSListing202606.csv", encoding="cp1252", low_memory = False)

list = pd.concat([globals()[f'list{i}'] for i in range(1, 31)], ignore_index=True)

In [221]:
#Confirming row count before and after concatenation for listing data
rows_list_pre = sum(len(globals()[f'list{i}']) for i in range(1, 31))
rows_list_post = len(list)

print(f"Before: {rows_list_pre:,} | After: {rows_list_post:,}")

Before: 967,143 | After: 967,143

In [222]:
#Aggregating all sold files into "sold"
sold1 = pd.read_csv("CRMLSSold202401_filled.csv").drop(columns = ["latfilled", "lonfilled"])
sold2 = pd.read_csv("CRMLSSold202401.csv")
sold3 = pd.read_csv("CRMLSSold202402.csv")
sold4 = pd.read_csv("CRMLSSold202403_filled.csv").drop(columns = ["latfilled", "lonfilled"])
sold5 = pd.read_csv("CRMLSSold202403.csv")
sold6 = pd.read_csv("CRMLSSold202404_filled.csv").drop(columns = ["latfilled", "lonfilled"])
sold7 = pd.read_csv("CRMLSSold202404.csv")
sold8 = pd.read_csv("CRMLSSold202405_filled.csv").drop(columns = ["latfilled", "lonfilled"])
sold9 = pd.read_csv("CRMLSSold202406_filled.csv").drop(columns = ["latfilled", "lonfilled"])
sold10 = pd.read_csv("CRMLSSold202407_filled.csv").drop(columns = ["latfilled", "lonfilled"])
sold11 = pd.read_csv("CRMLSSold202408.csv")
sold12 = pd.read_csv("CRMLSSold202409.csv")
sold13 = pd.read_csv("CRMLSSold202410.csv")
sold14 = pd.read_csv("CRMLSSold202411.csv")
sold15 = pd.read_csv("CRMLSSold202412.csv")
sold16 = pd.read_csv("CRMLSSold202501_filled.csv").drop(columns = ["latfilled", "lonfilled"])
sold17 = pd.read_csv("CRMLSSold202502.csv")
sold18 = pd.read_csv("CRMLSSold202503.csv")
sold19 = pd.read_csv("CRMLSSold202504.csv")
sold20 = pd.read_csv("CRMLSSold202505.csv")
sold21 = pd.read_csv("CRMLSSold202506.csv")
sold22 = pd.read_csv("CRMLSSold202507.csv")
sold23 = pd.read_csv("CRMLSSold202508.csv")
sold24 = pd.read_csv("CRMLSSold202509.csv")
sold25 = pd.read_csv("CRMLSSold202510.csv")
sold26 = pd.read_csv("CRMLSSold202511.csv")
sold27 = pd.read_csv("CRMLSSold202512.csv")
sold28 = pd.read_csv("CRMLSSold202601.csv")
sold29 = pd.read_csv("CRMLSSold202602.csv")
sold30 = pd.read_csv("CRMLSSold202603.csv")
sold31 = pd.read_csv("CRMLSSold202604.csv")
sold32 = pd.read_csv("CRMLSSold202605.csv", encoding="cp1252")
sold33 = pd.read_csv("CRMLSSold202606.csv", encoding="cp1252")

sold = pd.concat([globals()[f'sold{i}'] for i in range(1, 34)], ignore_index=True)

C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\1489320431.py:7: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  sold6 = pd.read_csv("CRMLSSold202404_filled.csv").drop(columns = ["latfilled", "lonfilled"])
C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\1489320431.py:8: DtypeWarning: Columns (2,36,39,56,74) have mixed types. Specify dtype option on import or set low_memory=False.
  sold7 = pd.read_csv("CRMLSSold202404.csv")
C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\1489320431.py:22: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  sold21 = pd.read_csv("CRMLSSold202506.csv")
C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\1489320431.py:29: DtypeWarning: Columns (4,74) have mixed types. Specify dtype option on import or set low_memory=False.
  sold28 = pd.read_csv("CRMLSSold202601.csv")

In [223]:
#Confirming row count before and after concatenation for sold data
rows_sold_pre = sum(len(globals()[f'sold{i}']) for i in range(1, 34))
rows_sold_post = len(sold)

print(f"Before: {rows_sold_pre:,} | After: {rows_sold_post:,}")

Before: 731,403 | After: 731,403

In [224]:
#Filter "list" to residential properties and confirming row count before and after filter
list_resid = list[list["PropertyType"] == "Residential"]
print(f"(Listing) Before: {len(list):,} | After: {len(list_resid):,}")

(Listing) Before: 967,143 | After: 615,688

In [225]:
#Filter "sold" to residential properties and confirming row count before and after filter
sold_resid = sold[sold["PropertyType"] == "Residential"]
print(f"(Sold) Before:{len(sold):,} | After: {len(sold_resid):,}")

(Sold) Before:731,403 | After: 492,311

In [226]:
#Save as new CSV files (w/ residential only filter)
list_resid.to_csv("w1_list_resid.csv", index=False)
sold_resid.to_csv("w1_sold_resid.csv", index=False)

<hr>

### **Week 2** — Dataset Structuring and Validation (EDA)

In [227]:
#Inspecting structure
sold.columns

Index(['Flooring', 'ViewYN', 'WaterfrontYN', 'BasementYN', 'PoolPrivateYN',
       'OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'MlsStatus', 'ElementarySchool',
       'AttachedGarageYN', 'ParkingTotal', 'BuilderName', 'PropertySubType',
       'LotSizeAcres', 'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'ListingId',
       'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'BuyerAgentAOR', 'ListAgentAOR', 'OriginatingSystemName',
       'OriginatingSystemSubName'],
      dtype='object')

In [228]:
pd.set_option('display.max_columns', None)
sold.head()

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,FireplacesTotal,AssociationFeeFrequency,AboveGradeFinishedArea,ListingKeyNumeric,MLSAreaMajor,TaxAnnualAmount,CountyOrParish,MlsStatus,ElementarySchool,AttachedGarageYN,ParkingTotal,BuilderName,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,BuyerAgencyCompensationType,StreetNumberNumeric,ListingId,BathroomsTotalInteger,City,BuyerAgencyCompensation,TaxYear,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,ElementarySchoolDistrict,CoBuyerAgentFirstName,PurchaseContractDate,ListingContractDate,BelowGradeFinishedArea,BusinessType,StateOrProvince,CoveredSpaces,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgentAOR,ListAgentAOR,OriginatingSystemName,OriginatingSystemSubName
0,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,Joan,Wachter,37.566106,-122.327954,1 Baldwin Avenue 411,Residential,1140.0,295000.0,777,Coldwell Banker Realty,Bay Area Senior Services,NaN,Joan Wachter,NaN,NaN,ML5090968,Scott,Withrow,NaN,Monthly,NaN,551985747,699 - Not Defined,NaN,San Mateo,Closed,NaN,False,1.0,NaN,Condominium,NaN,NaN,MLSListings,1988.0,Item1,1.0,ML81865679,2.0,San Mateo,2.5,NaN,NaN,2.0,2024-01-26,NaN,NaN,2023-11-22,2021-10-06,NaN,NaN,CA,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,False,1.0,Other,94401,6472.0,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,2024-01-24,950.0,Elizabeth,Brown,34.529407,-117.319674,15770 Mojave Drive L,CommercialLease,NaN,808.0,901,Lee & Associates,Lee & Associates,NaN,Elizabeth Brown,NaN,NaN,HD11042,Elizabeth,Brown,NaN,NaN,NaN,535486633,NaN,NaN,San Bernardino,Closed,NaN,NaN,NaN,NaN,Retail,1.2000,NaN,HighDesert,1980.0,Item1,15770.0,538013,NaN,Victorville,3.0,NaN,NaN,NaN,2024-01-24,NaN,NaN,2024-01-24,2021-08-06,NaN,Other,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,52320.0,NaN,NaN,NaN,NaN,92394,NaN,52320.0,NaN,NaN,NaN,NaN,NaN
2,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,2024-01-16,45000.0,Joseph,Piteleski,35.618009,-118.473141,0 Shadow mountain Dr.,Land,NaN,75000.0,865,Keller Williams OC Coastal Realty,Keller Williams OC Coastal Realty,NaN,Joseph Piteleski,NaN,NaN,spitejos,Joseph,Piteleski,NaN,NaN,NaN,529986282,LKIS - Lake Isabella,NaN,Kern,Closed,NaN,NaN,NaN,NaN,NaN,4.9900,NaN,OrangeCounty,NaN,Item1,0.0,OC21157144,NaN,Lake Isabella,3.0,NaN,NaN,NaN,2024-01-16,NaN,NaN,2023-12-22,2021-07-18,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,217364.0,NaN,False,NaN,NaN,93240,NaN,217364.0,NaN,NaN,NaN,NaN,NaN
3,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,2024-01-08,141500.0,CAROL,SMITH,34.396733,-117.220954,20171 Riverview Road,Land,NaN,145000.0,830,Keller Williams Realty Phelan,Coldwell Banker Home Source,Keller Williams Realty Phelan,CAROL SMITH,DINA,VELEZ,HD12177,Stacey,Hart,NaN,NaN,NaN,529618166,NaN,NaN,San Bernardino,Closed,NaN,NaN,NaN,NaN,NaN,5.0000,NaN,HighDesert,NaN,Item1,20171.0,537165,NaN,Apple Valley,3.0,NaN,NaN,NaN,2024-01-08,NaN,NaN,2023-10-24,2021-07-14,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,Irregular,217800.0,NaN,False,NaN,NaN,92308,NaN,217800.0,NaN,NaN,NaN,NaN,NaN
4,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,2024-01-17,15000.0,Jeremie,Tavisola,34.454756,-117.782248,0 Vac/Vic Avenue Z/195 Ste,Land,NaN,19500.0,805,Realty ONE Group West,Realty ONE Group West,NaN,Jeremie Tavisola,NaN,NaN,TTaviJer,Jeremie,Tavisola,NaN,NaN,NaN,522614340,LLO - Llano,NaN,Los Angeles,Closed,NaN,NaN,NaN,NaN,NaN,2.4996,NaN,SouthwestRiversideCounty,NaN,Item1,0.0,SW21124240,NaN,Llano,2.5,2011.0,NaN,NaN,2024-01-17,NaN,NaN,2023-08-25,2021-06-07,NaN,NaN,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108883.0,NaN,False,NaN,NaN,93544,0.0,108883.0,NaN,NaN,NaN,NaN,NaN

In [229]:
sold.dtypes

Flooring                         object
ViewYN                           object
WaterfrontYN                     object
BasementYN                       object
PoolPrivateYN                    object
                                 ...
MiddleOrJuniorSchoolDistrict    float64
BuyerAgentAOR                    object
ListAgentAOR                     object
OriginatingSystemName            object
OriginatingSystemSubName         object
Length: 82, dtype: object

In [230]:
#Unique property types found
sold["PropertyType"].value_counts()

PropertyType
Residential            492311
ResidentialLease       166788
Land                    24008
ManufacturedInPark      19852
ResidentialIncome       19567
CommercialSale           4544
CommercialLease          3836
BusinessOpportunity       497
Name: count, dtype: int64

#### Focusing on residential properties, including:
* "Residential": standard homes intended for owner-occupany

All properties for lease or bought as finanical investment for rental income were excluded for consistency of analysis of closing prices.
* "ResidentialLease": residential properties offered for rent
* "ResidentialIncome": multi-family properties containing 2 to 4 housing units that are sold together as a single investment

Additionally, I chose to focus on traditional residential home sales and excluded "ManufacturedInPark" homes (mobile homes) located in mobile home parks because they differ from site-built in terms of ownership structure, financing, depreciation, and market dyanmics. Since  mix mobil/manufactured homes and traditional site-built residential represent fundamentally different asset classes analyzing them together can severely skew metrics.

In [231]:
sold_resid = sold[sold["PropertyType"] == "Residential"]

In [232]:
#Validate completeness for sold data
null_report_sold = pd.DataFrame({
    "Null Count": sold_resid.isnull().sum(),
    "Null %": (sold_resid.isnull().sum() / len(sold_resid) * 100).round(2)
})

null_report_sold["Flag (>90% null)"] = null_report_sold["Null %"] > 90

null_report_sold = null_report_sold.sort_values("Null %", ascending=False)
null_report_sold

                          Null Count  Null %  Flag (>90% null)
TaxAnnualAmount               492311   100.0              True
AboveGradeFinishedArea        492311   100.0              True
TaxYear                       492311   100.0              True
ElementarySchoolDistrict      492311   100.0              True
CoveredSpaces                 492311   100.0              True
...                              ...     ...               ...
ListingKeyNumeric                  0     0.0             False
ListingContractDate                1     0.0             False
StateOrProvince                    1     0.0             False
BedroomsTotal                     13     0.0             False
PostalCode                         4     0.0             False

[82 rows x 3 columns]

I dropped columns with 90% or more missing values to improve the quality and reliability of my dataset. These columns did not contain enough data to support meaningful analysis, and any results based on them would likely be unstable or biased due to the very small number of valid entries. Removing them also helped simplify my dataset and reduce noise, making my analysis more accurate and easier to interpret.

I also dropped rows with missing closing price because the closing price is essential for analyzing sales and calculating meaningful metrics like average price, trends, and comparisons. Without it, those records cannot be reliably used in price-based analysis, so removing them ensures the results are accurate and consistent.

In [233]:
drop_cols_sold = null_report_sold[null_report_sold["Flag (>90% null)"]].index
sold_resid = sold_resid.drop(columns=drop_cols_sold)

sold_resid = sold_resid.dropna(subset=["ClosePrice"])

#### Numeric distribution summary, Sold (min, max, mean, median, percentiles) for ClosePrice, LivingArea, and DaysOnMarket

In [234]:
#Numeric distribution summary for sold data
cols = ['ClosePrice', 'LivingArea', 'DaysOnMarket']

summary_sold = pd.DataFrame({
    'min': sold_resid[cols].min(),
    'max': sold_resid[cols].max(),
    'mean': sold_resid[cols].mean(),
    'median': sold_resid[cols].median(),
    '25%': sold_resid[cols].quantile(0.25),
    '75%': sold_resid[cols].quantile(0.75)
})

summary_sold

                min          max          mean    median       25%        75%
ClosePrice      0.0  989500000.0  1.185593e+06  823000.0  575000.0  1300000.0
LivingArea      0.0   17021321.0  1.898896e+03    1644.0    1248.0     2222.0
DaysOnMarket -288.0      12430.0  3.689590e+01      18.0       8.0       47.0

#### Repeat for listing dataset

In [235]:
list.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1'],
      dtype='object')

In [236]:
list.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,PropertyType,LivingArea,ListPrice,DaysOnMarket,ListOfficeName,BuyerOfficeName,CoListOfficeName,ListAgentFullName,CoListAgentFirstName,CoListAgentLastName,BuyerAgentMlsId,BuyerAgentFirstName,BuyerAgentLastName,FireplacesTotal,AssociationFeeFrequency,AboveGradeFinishedArea,ListingKeyNumeric,MLSAreaMajor,TaxAnnualAmount,CountyOrParish,PropertyType.1,MlsStatus,ElementarySchool,ListAgentFirstName.1,AttachedGarageYN,ParkingTotal,BuilderName,PropertySubType,LotSizeAcres,SubdivisionName,BuyerOfficeAOR,YearBuilt,DaysOnMarket.1,BuyerAgencyCompensationType,StreetNumberNumeric,LivingArea.1,ListingId,BathroomsTotalInteger,City,BuyerAgencyCompensation,TaxYear,BuildingAreaTotal,BedroomsTotal,ContractStatusChangeDate,Longitude.1,ElementarySchoolDistrict,CoBuyerAgentFirstName,PurchaseContractDate,ListingContractDate,BelowGradeFinishedArea,BusinessType,Latitude.1,ListPrice.1,StateOrProvince,CoveredSpaces,MiddleOrJuniorSchool,FireplaceYN,Stories,HighSchool,Levels,ListAgentLastName.1,CloseDate.1,LotSizeDimensions,LotSizeArea,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,ManufacturedInPark,960.0,90000.0,0,CENTURY 21 CITRUS REALTY INC,NaN,NaN,Miriam Lara,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1075010398,614 - Covina,NaN,Los Angeles,ManufacturedInPark,Active,NaN,Miriam,False,4.0,NaN,NaN,NaN,NaN,NaN,1960.0,0,Item,1045.0,960.0,CV24093347,1.0,Covina,2500.0,NaN,NaN,4.0,2024-01-29,-117.909653,NaN,NaN,NaN,2024-01-29,NaN,NaN,34.097939,90000.0,CA,NaN,NaN,NaN,1.0,NaN,One,Lara,NaN,NaN,NaN,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,CommercialSale,NaN,1500000.0,0,Judson Real Estate,NaN,Judson Real Estate,Janelle Judson,Lynn,Judson,NaN,NaN,NaN,NaN,NaN,NaN,1074974457,92025 - Escondido,NaN,San Diego,CommercialSale,Active,NaN,Janelle,NaN,0.0,NaN,Retail,NaN,NaN,NaN,1940.0,0,Item1,NaN,NaN,NDP2403932,0.0,Escondido,2.0,NaN,3000.0,NaN,2024-01-11,-117.081614,NaN,NaN,NaN,2024-01-11,NaN,NaN,33.121241,1500000.0,CA,NaN,NaN,NaN,NaN,NaN,NaN,Judson,NaN,NaN,3052.0,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,Residential,1301.0,1340000.0,127,Rodeo Realty- Brentwood,NaN,NaN,Haleh Dowlatshahi,NaN,NaN,NaN,NaN,NaN,NaN,Monthly,NaN,1074973329,C05 - Westwood - Century City,NaN,Los Angeles,Residential,Pending,NaN,Haleh,NaN,0.0,NaN,Condominium,4.0831,NaN,NaN,1964.0,127,Item1,2220.0,1301.0,24389291,2.0,Los Angeles,2.0,NaN,1301.0,2.0,2024-05-07,-118.408445,NaN,NaN,2024-05-07,2024-01-01,NaN,NaN,34.052207,1340000.0,CA,NaN,NaN,False,1.0,NaN,One,Dowlatshahi,NaN,NaN,177861.0,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,Residential,2788.0,2500000.0,1,Your Home Sold Guaranteed Realty,NaN,NaN,Renee Chen,NaN,NaN,NaN,NaN,NaN,NaN,Monthly,NaN,1074954552,LNSLT - Salt Creek,NaN,Orange,Residential,Active,NaN,Renee,True,3.0,NaN,SingleFamilyResidence,0.1217,Warmington Homes (BB) (BBW),NaN,1994.0,1,Item1,16.0,2788.0,AR24091628,3.0,Laguna Niguel,2.0,NaN,NaN,4.0,2024-01-24,-117.691677,NaN,NaN,NaN,2024-01-24,NaN,NaN,33.496363,2500000.0,CA,NaN,NaN,True,2.0,NaN,Two,Chen,NaN,NaN,5300.0,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,Residential,3250.0,3150000.0,1,COMPASS,NaN,NaN,Margaret Nader,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1074936537,655 - San Marino,NaN,Los Angeles,Residential,Active,NaN,Margaret,True,2.0,NaN,SingleFamilyResidence,0.2159,NaN,NaN,1965.0,1,Item1,1615.0,3250.0,P1-17547,4.0,San Marino,2.5,NaN,NaN,6.0,2024-01-12,-118.111254,NaN,NaN,NaN,2024-01-12,NaN,NaN,34.119345,3150000.0,CA,NaN,NaN,True,2.0,NaN,Two,Nader,NaN,NaN,9404.0,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road

In [237]:
list.dtypes

OriginalListPrice               float64
ListingKey                        int64
ListAgentEmail                   object
CloseDate                        object
ClosePrice                      float64
                                 ...
BuyerOfficeName.1                object
AssociationFee                  float64
LotSizeSquareFeet               float64
MiddleOrJuniorSchoolDistrict    float64
UnparsedAddress.1                object
Length: 84, dtype: object

In [238]:
list["PropertyType"].value_counts()

PropertyType
Residential            615688
ResidentialLease       199989
Land                    62804
ResidentialIncome       36096
ManufacturedInPark      27557
CommercialSale          13216
CommercialLease          8736
BusinessOpportunity      3057
Name: count, dtype: int64

In [239]:
#Applying same residential classification and filter to listing data
list_resid = list[list["PropertyType"] == "Residential"]

In [240]:
#Validate completeness for listing data
null_report_list = pd.DataFrame({
    "Null Count": list_resid.isnull().sum(),
    "Null %": (list_resid.isnull().sum() / len(list_resid) * 100).round(2)
})

null_report_list["Flag (>90% null)"] = null_report_list["Null %"] > 90

null_report_list = null_report_list.sort_values("Null %", ascending=False)
null_report_list

                          Null Count  Null %  Flag (>90% null)
TaxYear                       615688   100.0              True
TaxAnnualAmount               615688   100.0              True
AboveGradeFinishedArea        615688   100.0              True
FireplacesTotal               615688   100.0              True
ElementarySchoolDistrict      615688   100.0              True
...                              ...     ...               ...
ListingKeyNumeric                  0     0.0             False
MlsStatus                          0     0.0             False
ListingContractDate                0     0.0             False
ListPrice.1                        0     0.0             False
PostalCode                        21     0.0             False

[84 rows x 3 columns]

Applying the same logic for the sold data, I also dropped columns with 90% or more missing values for the listing data. Additionally, duplicate columns ended with ".1" were also droppped for redundant data.

I did not drop observations with missing closing price as it is natural and justified that not all real estate listed is going to be sold within the time frame the data was pulled.

In [241]:
drop_cols_list = null_report_list[null_report_list["Flag (>90% null)"]].index
list_resid = list_resid.drop(columns=drop_cols_list)
list_resid = list_resid.drop(columns=list_resid.columns[list_resid.columns.str.contains(r'\.1')])

list_resid.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'AssociationFeeFrequency', 'ListingKeyNumeric',
       'MLSAreaMajor', 'CountyOrParish', 'MlsStatus', 'ElementarySchool',
       'AttachedGarageYN', 'ParkingTotal', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'ListingId',
       'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'BedroomsTotal', 'ContractStatusChangeDate', 'PurchaseContractDate',
       'ListingContractDate', 'StateOrProvince', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'LotSizeArea',
       'MainLevelBedrooms', 'NewConstructionYN', 'GarageSpaces',
       'HighSchoolDistrict', 'PostalCode', 'AssociationFee',
       'LotSizeSquareFeet'],
      dtype='object')

#### Numeric distribution summary, Listing (min, max, mean, median, percentiles) for ClosePrice, LivingArea, and DaysOnMarket

In [242]:
#Numeric distribution summary for listing data
cols = ['ClosePrice', 'LivingArea', 'DaysOnMarket']

summary_list = pd.DataFrame({
    'min': list_resid[cols].min(),
    'max': list_resid[cols].max(),
    'mean': list_resid[cols].mean(),
    'median': list_resid[cols].median(),
    '25%': list_resid[cols].quantile(0.25),
    '75%': list_resid[cols].quantile(0.75)
})

summary_list

                min          max          mean    median       25%        75%
ClosePrice    525.0  820000000.0  1.212975e+06  860000.0  600000.0  1358866.0
LivingArea      0.0   17021321.0  1.979483e+03    1672.0    1248.0     2303.0
DaysOnMarket  -58.0       1063.0  1.839239e+01      11.0       5.0       22.0

In [243]:
#Save filtered dataset as new CSV (for different types of residential property types and drops)
list_resid.to_csv("w2_list_resid.csv", index=False)
sold_resid.to_csv("w2_sold_resid.csv", index=False)

<hr>

### **Week 3** — Mortgage Rate Enrichment

In [244]:
#Fetch mortgage rate data from FRED
url = "https://fred.stlouisfed.org/graph/fredgraph.csv?id=MORTGAGE30US"
mortgage = pd.read_csv(url, parse_dates=['observation_date'])
mortgage.columns = ['date', 'rate_30yr_fixed']
mortgage

           date  rate_30yr_fixed
0    1971-04-02             7.33
1    1971-04-09             7.31
2    1971-04-16             7.31
3    1971-04-23             7.31
4    1971-04-30             7.29
...         ...              ...
2882 2026-06-25             6.49
2883 2026-07-02             6.43
2884 2026-07-09             6.49
2885 2026-07-16             6.55
2886 2026-07-23             6.58

[2887 rows x 2 columns]

In [245]:
#Resampling weekly rates to monthly averages
mortgage['year_month'] = mortgage['date'].dt.to_period('M')
mortgage_monthly = mortgage.groupby('year_month')['rate_30yr_fixed'].mean().reset_index()

#### Create matching year_month key on MLS datasets

In [246]:
#Sold dataset — key off CloseDate
sold = pd.read_csv("w2_sold_resid.csv")
sold['year_month'] = pd.to_datetime(sold['CloseDate']).dt.to_period('M')

#Listings dataset — key off ListingContractDate
listing = pd.read_csv("w2_list_resid.csv")
listing['year_month'] = pd.to_datetime(listing['ListingContractDate']).dt.to_period('M')

C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\1582859558.py:2: DtypeWarning: Columns (5,39,51,63,64,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv("w2_sold_resid.csv")
C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\1582859558.py:6: DtypeWarning: Columns (2,36) have mixed types. Specify dtype option on import or set low_memory=False.
  listing = pd.read_csv("w2_list_resid.csv")

In [247]:
#Merge
sold_with_rates = sold.merge(mortgage_monthly, on='year_month', how='left')
listing_with_rates = listing.merge(mortgage_monthly, on='year_month', how='left')

In [248]:
#Validate merge - check for unmatched rows (rate should not be null)
print(sold_with_rates['rate_30yr_fixed'].isnull().sum())
print(listing_with_rates['rate_30yr_fixed'].isnull().sum())

0
0

In [249]:
#Preview
print(sold_with_rates[['CloseDate', 'year_month', 'ClosePrice', 'rate_30yr_fixed']].head())

    CloseDate year_month  ClosePrice  rate_30yr_fixed
0  2024-01-26    2024-01    240000.0           6.6425
1  2024-01-05    2024-01    815000.0           6.6425
2  2024-01-05    2024-01    810000.0           6.6425
3  2024-01-02    2024-01   2100000.0           6.6425
4  2024-01-22    2024-01   1950000.0           6.6425

In [250]:
#Save enriched datasets as new CSVs
sold_with_rates.to_csv("w3_sold_fred.csv", index=False)
listing_with_rates.to_csv("w3_list_fred.csv", index=False)

<hr>

### **Week 4-5** —  Data Cleaning and Preparation

In [251]:
#Import full data
sold_with_rates = pd.read_csv("w3_sold_fred.csv")
listing_with_rates = pd.read_csv("w3_list_fred.csv")

C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\226531304.py:2: DtypeWarning: Columns (5,39,51,63,64,65,66) have mixed types. Specify dtype option on import or set low_memory=False.
  sold_with_rates = pd.read_csv("w3_sold_fred.csv")
C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\226531304.py:3: DtypeWarning: Columns (2,36) have mixed types. Specify dtype option on import or set low_memory=False.
  listing_with_rates = pd.read_csv("w3_list_fred.csv")

In [252]:
#Inspecting format of date-related columns
date_columns = ["CloseDate", "PurchaseContractDate", "ListingContractDate", "ContractStatusChangeDate"]

print(f"Sold:\n{sold_with_rates[date_columns].dtypes}")
print()
print(f"Listing:\n{listing_with_rates.dtypes[date_columns]}")

Sold:
CloseDate                   object
PurchaseContractDate        object
ListingContractDate         object
ContractStatusChangeDate    object
dtype: object

Listing:
CloseDate                   object
PurchaseContractDate        object
ListingContractDate         object
ContractStatusChangeDate    object
dtype: object

In [253]:
#Convert date fields to datetime format
sold_with_rates[date_columns] = sold_with_rates[date_columns].apply(pd.to_datetime)
listing_with_rates[date_columns] = listing_with_rates[date_columns].apply(pd.to_datetime)

print(f"Sold:\n{sold_with_rates[date_columns].dtypes}")
print()
print(f"Listing:\n{listing_with_rates.dtypes[date_columns]}")

Sold:
CloseDate                   datetime64[ns]
PurchaseContractDate        datetime64[ns]
ListingContractDate         datetime64[ns]
ContractStatusChangeDate    datetime64[ns]
dtype: object

Listing:
CloseDate                   datetime64[ns]
PurchaseContractDate        datetime64[ns]
ListingContractDate         datetime64[ns]
ContractStatusChangeDate    datetime64[ns]
dtype: object

#### Date Consistency Checks

In [254]:
#Validate the logical order of date fields: ListingContractDate should precede PurchaseContractDate, which should precede CloseDate
sold_with_rates["listing_after_close_flag"] = (sold_with_rates["ListingContractDate"] > sold_with_rates["CloseDate"])

sold_with_rates["purchase_after_close_flag"] = (sold_with_rates["PurchaseContractDate"] > sold_with_rates["CloseDate"])

sold_with_rates["negative_timeline_flag"] = (
    (sold_with_rates["ListingContractDate"] > sold_with_rates["PurchaseContractDate"]) |
    (sold_with_rates["PurchaseContractDate"] > sold_with_rates["CloseDate"]) |
    (sold_with_rates["ListingContractDate"] > sold_with_rates["CloseDate"])
)

In [255]:
#Flag columns that violate rules as True
flag_columns = [
    "listing_after_close_flag",
    "purchase_after_close_flag",
    "negative_timeline_flag"
]

print("Sold:")
print(sold_with_rates[flag_columns].sum())

Sold:
listing_after_close_flag      73
purchase_after_close_flag    291
negative_timeline_flag       607
dtype: int64

In [256]:
#Remove rows that violate logical time order
rows_before = len(sold_with_rates)

sold_timely = sold_with_rates[~sold_with_rates["negative_timeline_flag"]]
rows_after = len(sold_timely)

print("Sold (time cleaning):")
print(f"Rows before: {rows_before:,}")
print(f"Rows after: {rows_after:,}")
print(f"Rows removed: {rows_before - rows_after:,}")

Sold (time cleaning):
Rows before: 492,309
Rows after: 491,702
Rows removed: 607

In [257]:
#Repeat date check for listing data
listing_with_rates["listing_after_close_flag"] = (listing_with_rates["ListingContractDate"] > listing_with_rates["CloseDate"])

listing_with_rates["purchase_after_close_flag"] = (listing_with_rates["PurchaseContractDate"] > listing_with_rates["CloseDate"])

listing_with_rates["negative_timeline_flag"] = (
    (listing_with_rates["ListingContractDate"] > listing_with_rates["PurchaseContractDate"]) |
    (listing_with_rates["PurchaseContractDate"] > listing_with_rates["CloseDate"]) |
    (listing_with_rates["ListingContractDate"] > listing_with_rates["CloseDate"])
)

print("Listing (time cleaning):")
print(listing_with_rates[flag_columns].sum())

rows_before = len(listing_with_rates)

list_timely = listing_with_rates[~listing_with_rates["negative_timeline_flag"]]
rows_after = len(list_timely)

print()
print(f"Rows before: {rows_before:,}")
print(f"Rows after: {rows_after:,}")
print(f"Rows removed: {rows_before - rows_after:,}")

Listing (time cleaning):
listing_after_close_flag      84
purchase_after_close_flag    268
negative_timeline_flag       568
dtype: int64

Rows before: 615,688
Rows after: 615,120
Rows removed: 568

#### Geographic Data Checks

In [258]:
#Flag records with missing coordinates
sold_timely["missing_cords"] = (sold_timely["Latitude"] == 0) | sold_timely["Longitude"] == 0

#Flag implausible or out-of_state coordinates 
#Latitude: Between 32.5343 and 42.0095
#Longitude: Between -124.4323 and -114.1312
sold_timely["invalid_cords"] = (
    (sold_timely["Latitude"] < 32.5343) |
    (sold_timely["Latitude"] > 42.0095) |
    (sold_timely["Longitude"] < -124.4323) |
    (sold_timely["Longitude"] > -114.1312)
)

missing = len(sold_timely[(sold_timely["missing_cords"] == True)])
invalid = len(sold_timely[(sold_timely["invalid_cords"] == True)])

print("Sold:")
print(f"Missing Coordinates: {missing:,}")
print(f"Invalid Coordinates: {invalid:,}")
print(f"Total: {(missing + invalid):,}")

Sold:
Missing Coordinates: 16,214
Invalid Coordinates: 110
Total: 16,324

C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\4124117517.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sold_timely["missing_cords"] = (sold_timely["Latitude"] == 0) | sold_timely["Longitude"] == 0
C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\4124117517.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sold_timely["invalid_cords"] = (

In [259]:
#Remove fields with missing or invalid coordinates for accurate Califlorina-only analysis
sold_geo = sold_timely[~(sold_timely["invalid_cords"] | sold_timely["missing_cords"])]

rows_before = len(sold_timely)
rows_after = len(sold_geo)

print("Sold (coordinate cleaning):")
print(f"Rows before: {rows_before:,}")
print(f"Rows after: {rows_after:,}")
print(f"Rows removed: {rows_before - rows_after:,}")

Sold (coordinate cleaning):
Rows before: 491,702
Rows after: 475,378
Rows removed: 16,324

In [260]:
#Repeat for geographic check for listing data
list_timely["missing_cords"] = (list_timely["Latitude"] == 0) | list_timely["Longitude"] == 0

list_timely["invalid_cords"] = (
    (list_timely["Latitude"] < 32.5343) |
    (list_timely["Latitude"] > 42.0095) |
    (list_timely["Longitude"] < -124.4323) |
    (list_timely["Longitude"] > -114.1312)
)

missing = len(list_timely[(list_timely["missing_cords"] == True)])
invalid = len(list_timely[(list_timely["invalid_cords"] == True)])

print()
print("Listing (coordinate cleaning):")
print(f"Missing Coordinates: {missing:,}")
print(f"Invalid Coordinates: {invalid:,}")
print(f"Total: {(missing + invalid):,}")

list_geo = list_timely[~(list_timely["invalid_cords"] | list_timely["missing_cords"])]

rows_before = len(list_timely)
rows_after = len(list_geo)

print()
print(f"Rows before: {rows_before:,}")
print(f"Rows after: {rows_after:,}")
print(f"Rows removed: {rows_before - rows_after:,}")

Listing (coordinate cleaning):
Missing Coordinates: 80,836
Invalid Coordinates: 353
Total: 81,189

C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\197388272.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  list_timely["missing_cords"] = (list_timely["Latitude"] == 0) | list_timely["Longitude"] == 0
C:\Users\liny0\AppData\Local\Temp\ipykernel_29280\197388272.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  list_timely["invalid_cords"] = (

Rows before: 615,120
Rows after: 533,931
Rows removed: 81,189

#### Adding school district mapping

In [261]:
#Import for Califlorina school distric data
import geopandas as gpd

school_district = gpd.read_file("DistrictAreas2526.geojson")

#Keep only unified school districts
school_unified = school_district[school_district["DistrictType"] == "Unified"].copy()

#Convert sold dataset to GeoDataFrame
sold_geo = gpd.GeoDataFrame(sold_geo, geometry=gpd.points_from_xy(sold_geo["Longitude"], sold_geo["Latitude"]), crs="EPSG:4326")
school_unified = school_unified.to_crs(sold_geo.crs)

#Spatial join and add resulting DistrictName as new column: "DistrictName"
sold_geo = gpd.sjoin(sold_geo, school_unified[["DistrictName", "geometry"]], how="left", predicate="within")
sold_geo = sold_geo.drop(columns="index_right")

#Number of unmatched listing properties
sold_geo["DistrictName"].isna().sum()

np.int64(114674)

In [262]:
#Repeat for lising data
#Convert listing dataset to GeoDataFrame
list_geo = gpd.GeoDataFrame(list_geo, geometry=gpd.points_from_xy(list_geo["Longitude"], list_geo["Latitude"]), crs="EPSG:4326")
school_unified = school_unified.to_crs(list_geo.crs)

#Spatial join and add resulting DistrictName as new column: "DistrictName"
list_geo = gpd.sjoin(list_geo, school_unified[["DistrictName", "geometry"]], how="left", predicate="within")
list_geo = list_geo.drop(columns="index_right")

#Number of unmatched listing properties
list_geo["DistrictName"].isna().sum()

np.int64(122374)

#### Remove invalid numeric values

In [263]:
#Remove invalid numeric values (no negative ClosePrice, LivingArea, DaysOnMarket, Bedrooms, or Bathrooms)
sold_clean = sold_geo[
    (sold_geo["ClosePrice"] > 0) &
    (sold_geo["LivingArea"] > 0) &
    (sold_geo["DaysOnMarket"] >= 0) &
    (sold_geo["BedroomsTotal"] >= 0) &
    (sold_geo["BathroomsTotalInteger"] >= 0)
]

rows_before = len(sold_geo)
rows_after = len(sold_clean)

print("Sold (invalids):")
print(f"Rows before: {rows_before:,}")
print(f"Rows after: {rows_after:,}")
print(f"Rows removed: {rows_before - rows_after:,}")

Sold (invalids):
Rows before: 475,378
Rows after: 474,802
Rows removed: 576

In [264]:
#Repeat for listing data
list_clean = list_geo[
    (list_geo["LivingArea"] > 0) &
    (list_geo["DaysOnMarket"] >= 0) &
    (list_geo["BedroomsTotal"] >= 0) &
    (list_geo["BathroomsTotalInteger"] >= 0)
]

rows_before = len(list_geo)
rows_after = len(list_clean)

print("Listing (invalids):")
print(f"Rows before: {rows_before:,}")
print(f"Rows after: {rows_after:,}")
print(f"Rows removed: {rows_before - rows_after:,}")

Listing (invalids):
Rows before: 533,931
Rows after: 532,854
Rows removed: 1,077

#### Final sweep through columns

In [265]:
#Summary of nan of sold
nan_percent = (sold_clean.isna().mean() * 100).round(2).sort_values(ascending=False)
print(nan_percent[nan_percent > 50])

ElementarySchool               86.65
MiddleOrJuniorSchool           86.51
BuyerAgencyCompensationType    83.70
BuyerAgencyCompensation        83.70
HighSchool                     82.44
OriginatingSystemSubName       81.85
OriginatingSystemName          81.85
CoListAgentFirstName           77.09
CoListAgentLastName            77.04
CoListOfficeName               76.43
SubdivisionName                63.39
AssociationFeeFrequency        58.20
dtype: float64

In [266]:
#Summary of nan of listing
nan_percent = (list_clean.isna().mean() * 100).round(2).sort_values(ascending=False)
print(nan_percent[nan_percent > 50])

BuyerAgencyCompensationType    89.33
BuyerAgencyCompensation        89.33
ElementarySchool               88.35
MiddleOrJuniorSchool           88.29
HighSchool                     84.52
CoListAgentFirstName           77.39
CoListAgentLastName            77.31
CoListOfficeName               77.31
ClosePrice                     75.52
BuyerOfficeAOR                 75.49
BuyerOfficeName                73.73
BuyerAgentFirstName            73.57
BuyerAgentMlsId                73.50
BuyerAgentLastName             73.48
CloseDate                      72.46
SubdivisionName                64.80
AssociationFeeFrequency        56.76
PurchaseContractDate           53.29
dtype: float64

In [267]:
#Removing unnecessary columns for sold and listing data, based on relevancy to market analysis and data availability
drop_sold = ["BuyerAgencyCompensationType"]
drop_list = ["BuyerAgencyCompensationType", "BuyerOfficeAOR"]

sold_clean = sold_clean.drop(columns=drop_sold)
list_clean = list_clean.drop(columns=drop_list)

In [268]:
#Remove flagging columns
sold_clean = sold_clean.drop(columns=["listing_after_close_flag", "purchase_after_close_flag", "negative_timeline_flag", "missing_cords", "invalid_cords"])
list_clean = list_clean.drop(columns=["listing_after_close_flag", "purchase_after_close_flag", "negative_timeline_flag", "missing_cords", "invalid_cords"])

In [269]:
#Final row count before and after cleaning
sold_before = len(sold_with_rates)
print("Final row count before and after cleaning")

print()
print("Sold:")
print(f"Rows before: {len(sold_with_rates):,}")
print(f"Rows after: {len(sold_clean):,}")
print(f"Rows removed: {len(sold_with_rates) - len(sold_clean):,}")

print()
print("Listing:")
print(f"Rows before: {len(listing_with_rates):,}")
print(f"Rows after: {len(list_clean):,}")
print(f"Rows removed: {len(listing_with_rates) - len(list_clean):,}")

Final row count before and after cleaning

Sold:
Rows before: 492,309
Rows after: 474,802
Rows removed: 17,507

Listing:
Rows before: 615,688
Rows after: 532,854
Rows removed: 82,834

In [270]:
#Save cleaned datasets as new CSVs
sold_clean.to_csv("w4_sold_clean.csv", index=False)
list_clean.to_csv("w4_listing_clean.csv", index=False)

<hr>

### **Week 6** —  Feature Engineering and Market Metrics